### PR TITLE
Add windows_reserved option to check for Windows reserved filenames

### LINKED ISSUE #7: Need tests for Windows/DOS reserved filenames
The following filenames are reserved on Windows/DOS, as they correspond to device names: CON, PRN, AUX, NUL, COM[1-9], LTP[1-9].

Files and directories should not have these names (case insensitive), nor should those names be a prefix for a file or directory, e.g. "con.smith.msg" or "aux.txt".

For DOS and OS/2, there are also device names CLOAK$$$, CLOCK, CLOCK$, CONFIG$, EMMXXX0, DPMIXXX0, DPMSXXX0, $IDLE$, IFS$HLP$, KEYBD$, LST, SCREEN$, VCPIXXX0, XMSXXXX0, RANDOM$, URANDOM$, PLT, KBD$, POINTER$.

### PR DESCRIPTION
**Pull request by robrwo**
This fixes #7.

For more information, see
https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx

### CODE REVIEW

**Comment by robrwo** [comment]
Any movement on this?

**Comment by abraxxa** [comment]
Sorry it took so long, I was hoping someone else would comment on it but this obviously didn't happen.

**Comment by karenetheridge** [comment]
This test is way too loose. See https://rt.cpan.org/Ticket/Display.html?id=123972

**Comment by abraxxa** [comment]
I guess the regex isn‘t ended with a $ anchor because the linked doc states that those reserved names shouldn‘t (how I hate that in RFCs!) be immediatly followed by an extension.
Imho that would fix the patch, do you agree?

**Comment by karenetheridge** [comment]
That would be enough to fix the problem here, but then it wouldn't follow the spec.

This is closer, I think:

    /^(CON|PRN|AUX|NUL|COM[1-9]|LPT[1-9])(\.[^.]+)?$/i

**Pull request merged**
